version: 2.1
orbs:
  python: circleci/python@2.1.1
  # heroku: circleci/heroku@1.2.6

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout # move on main branch
      - python/install-packages: # install all packages
          pkg-manager: pipenv
      - run:
          name: Check with Flake8
          command: flake8   # Run Flake8 to check your code
      - run:
          name: Run tests
          command: |
            pipenv shell
            mkdir test-results
            pytest --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: ~/project
          paths:
            - . 

  deploy: # this can be any name you choose
    executor: python/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
  test_my_app:
    jobs:
      - build_and_test
      
